const countries = { 
  "AD": { "country": "Andorra", "code": "AD" }, 
  "AE": { "country": "United Arab Emirates", "code": "AE" }, 
  "AF": { "country": "Afghanistan", "code": "AF" }, 
  "AG": { "country": "Antigua and Barbuda", "code": "AG" }, 
  "AI": { "country": "Anguilla", "code": "AI" }, 
  "AL": { "country": "Albania", "code": "AL" }, 
  "AM": { "country": "Armenia", "code": "AM" }, 
  "AO": { "country": "Angola", "code": "AO" }, 
  "AQ": { "country": "Antarctica", "code": "AQ" }, 
  "AR": { "country": "Argentina", "code": "AR" }, 
  "AT": { "country": "Austria", "code": "AT" }, 
  "AU": { "country": "Australia*", "code": "AU" }, 
  "AW": { "country": "Aruba", "code": "AW" }, 
  "AX": { "country": "Aland Islands", "code": "AX" }, 
  "AZ": { "country": "Azerbaijan", "code": "AZ" }, 
  "BA": { "country": "Bosnia and Herzegovina", "code": "BA" }, 
  "BB": { "country": "Barbados", "code": "BB" }, 
  "BD": { "country": "Bangladesh", "code": "BD" }, 
  "BE": { "country": "Belgium", "code": "BE" }, 
  "BF": { "country": "Burkina Faso", "code": "BF" }, 
  "BG": { "country": "Bulgaria", "code": "BG" }, 
  "BH": { "country": "Bahrain", "code": "BH" }, 
  "BI": { "country": "Burundi", "code": "BI" }, 
  "BJ": { "country": "Benin", "code": "BJ" }, 
  "BL": { "country": "Saint Barthélemy", "code": "BL" }, 
  "BM": { "country": "Bermuda", "code": "BM" }, 
  "BN": { "country": "Brunei Darussalam", "code": "BN" }, 
  "BO": { "country": "Bolivia, Plurinational State of", "code": "BO" }, 
  "BQ": { "country": "Bonaire, Sint Eustatius and Saba", "code": "BQ" }, 
  "BR": { "country": "Brazil*", "code": "BR" }, 
  "BS": { "country": "Bahamas", "code": "BS" }, 
  "BT": { "country": "Bhutan", "code": "BT" }, 
  "BV": { "country": "Bouvet Island", "code": "BV" }, 
  "BW": { "country": "Botswana", "code": "BW" }, 
  "BY": { "country": "Belarus", "code": "BY" }, 
  "BZ": { "country": "Belize", "code": "BZ" }, 
  "CA": { "country": "Canada*", "code": "CA" }, 
  "CC": { "country": "Cocos (Keeling) Islands", "code": "CC" }, 
  "CD": { "country": "Congo, the Democratic Republic of the", "code": "CD" }, 
  "CF": { "country": "Central African Republic", "code": "CF" }, 
  "CG": { "country": "Congo", "code": "CG" }, 
  "CH": { "country": "Switzerland", "code": "CH" }, 
  "CI": { "country": "Cote d’Ivoire", "code": "CI" }, 
  "CK": { "country": "Cook Islands", "code": "CK" }, 
  "CL": { "country": "Chile", "code": "CL" }, 
  "CM": { "country": "Cameroon", "code": "CM" }, 
  "CN": { "country": "China*", "code": "CN" }, 
  "CO": { "country": "Colombia", "code": "CO" }, 
  "CR": { "country": "Costa Rica", "code": "CR" }, 
  "CU": { "country": "Cuba", "code": "CU" }, 
  "CV": { "country": "Cape Verde", "code": "CV" }, 
  "CW": { "country": "Curaçao", "code": "CW" }, 
  "CX": { "country": "Christmas Island", "code": "CX" }, 
  "CY": { "country": "Cyprus", "code": "CY" }, 
  "CZ": { "country": "Czech Republic", "code": "CZ" }, 
  "DE": { "country": "Germany", "code": "DE" }, 
  "DJ": { "country": "Djibouti", "code": "DJ" }, 
  "DK": { "country": "Denmark", "code": "DK" }, 
  "DM": { "country": "Dominica", "code": "DM" }, 
  "DO": { "country": "Dominican Republic", "code": "DO" }, 
  "DZ": { "country": "Algeria", "code": "DZ" }, 
  "EC": { "country": "Ecuador", "code": "EC" }, 
  "EE": { "country": "Estonia", "code": "EE" }, 
  "EG": { "country": "Egypt", "code": "EG" }, 
  "EH": { "country": "Western Sahara", "code": "EH" }, 
  "ER": { "country": "Eritrea", "code": "ER" }, 
  "ES": { "country": "Spain", "code": "ES" }, 
  "ET": { "country": "Ethiopia", "code": "ET" }, 
  "FI": { "country": "Finland", "code": "FI" }, 
  "FJ": { "country": "Fiji", "code": "FJ" }, 
  "FK": { "country": "Falkland Islands (Malvinas)", "code": "FK" }, 
  "FO": { "country": "Faroe Islands", "code": "FO" }, 
  "FR": { "country": "France", "code": "FR" }, 
  "GA": { "country": "Gabon", "code": "GA" }, 
  "GB": { "country": "United Kingdom", "code": "GB" }, 
  "GD": { "country": "Grenada", "code": "GD" }, 
  "GE": { "country": "Georgia", "code": "GE" }, 
  "GF": { "country": "French Guiana", "code": "GF" }, 
  "GG": { "country": "Guernsey", "code": "GG" }, 
  "GH": { "country": "Ghana", "code": "GH" }, 
  "GI": { "country": "Gibraltar", "code": "GI" }, 
  "GL": { "country": "Greenland", "code": "GL" }, 
  "GM": { "country": "Gambia", "code": "GM" }, 
  "GN": { "country": "Guinea", "code": "GN" }, 
  "GP": { "country": "Guadeloupe", "code": "GP" }, 
  "GQ": { "country": "Equatorial Guinea", "code": "GQ" }, 
  "GR": { "country": "Greece", "code": "GR" }, 
  "GS": { "country": "South Georgia and the South Sandwich Islands", "code": "GS" }, 
  "GT": { "country": "Guatemala", "code": "GT" }, 
  "GW": { "country": "Guinea-Bissau", "code": "GW" }, 
  "GY": { "country": "Guyana", "code": "GY" }, 
  "HM": { "country": "Heard Island and McDonald Islands", "code": "HM" }, 
  "HN": { "country": "Honduras", "code": "HN" }, 
  "HR": { "country": "Croatia", "code": "HR" }, 
  "HT": { "country": "Haiti", "code": "HT" }, 
  "HU": { "country": "Hungary", "code": "HU" }, 
  "ID": { "country": "Indonesia", "code": "ID" }, 
  "IE": { "country": "Ireland*", "code": "IE" }, 
  "IL": { "country": "Israel", "code": "IL" }, 
  "IM": { "country": "Isle of Man", "code": "IM" }, 
  "IN": { "country": "India*", "code": "IN" }, 
  "IO": { "country": "British Indian Ocean Territory", "code": "IO" }, 
  "IQ": { "country": "Iraq", "code": "IQ" }, 
  "IR": { "country": "Iran, Islamic Republic of", "code": "IR" }, 
  "IS": { "country": "Iceland", "code": "IS" }, 
  "IT": { "country": "Italy*", "code": "IT" }, 
  "JE": { "country": "Jersey", "code": "JE" }, 
  "JM": { "country": "Jamaica", "code": "JM" }, 
  "JO": { "country": "Jordan", "code": "JO" }, 
  "JP": { "country": "Japan", "code": "JP" }, 
  "KE": { "country": "Kenya", "code": "KE" }, 
  "KG": { "country": "Kyrgyzstan", "code": "KG" }, 
  "KH": { "country": "Cambodia", "code": "KH" }, 
  "KI": { "country": "Kiribati", "code": "KI" }, 
  "KM": { "country": "Comoros", "code": "KM" }, 
  "KN": { "country": "Saint Kitts and Nevis", "code": "KN" }, 
  "KP": { "country": "Korea, Democratic People’s Republic of", "code": "KP" }, 
  "KR": { "country": "Korea, Republic of", "code": "KR" }, 
  "KW": { "country": "Kuwait", "code": "KW" }, 
  "KY": { "country": "Cayman Islands", "code": "KY" }, 
  "KZ": { "country": "Kazakhstan", "code": "KZ" }, 
  "LA": { "country": "Lao People’s Democratic Republic", "code": "LA" }, 
  "LB": { "country": "Lebanon", "code": "LB" }, 
  "LC": { "country": "Saint Lucia", "code": "LC" }, 
  "LI": { "country": "Liechtenstein", "code": "LI" }, 
  "LK": { "country": "Sri Lanka", "code": "LK" }, 
  "LR": { "country": "Liberia", "code": "LR" }, 
  "LS": { "country": "Lesotho", "code": "LS" }, 
  "LT": { "country": "Lithuania", "code": "LT" }, 
  "LU": { "country": "Luxembourg", "code": "LU" }, 
  "LV": { "country": "Latvia", "code": "LV" }, 
  "LY": { "country": "Libyan Arab Jamahiriya", "code": "LY" }, 
  "MA": { "country": "Morocco", "code": "MA" }, 
  "MC": { "country": "Monaco", "code": "MC" }, 
  "MD": { "country": "Moldova, Republic of", "code": "MD" }, 
  "ME": { "country": "Montenegro", "code": "ME" }, 
  "MF": { "country": "Saint Martin (French part)", "code": "MF" }, 
  "MG": { "country": "Madagascar", "code": "MG" }, 
  "MK": { "country": "Macedonia, the former Yugoslav Republic of", "code": "MK" }, 
  "ML": { "country": "Mali", "code": "ML" }, 
  "MM": { "country": "Myanmar", "code": "MM" }, 
  "MN": { "country": "Mongolia", "code": "MN" }, 
  "MO": { "country": "Macao", "code": "MO" }, 
  "MQ": { "country": "Martinique", "code": "MQ" }, 
  "MR": { "country": "Mauritania", "code": "MR" }, 
  "MS": { "country": "Montserrat", "code": "MS" }, 
  "MT": { "country": "Malta", "code": "MT" }, 
  "MU": { "country": "Mauritius", "code": "MU" }, 
  "MV": { "country": "Maldives", "code": "MV" }, 
  "MW": { "country": "Malawi", "code": "MW" }, 
  "MX": { "country": "Mexico*", "code": "MX" }, 
  "MY": { "country": "Malaysia", "code": "MY" }, 
  "MZ": { "country": "Mozambique", "code": "MZ" }, 
  "NA": { "country": "Namibia", "code": "NA" }, 
  "NC": { "country": "New Caledonia", "code": "NC" }, 
  "NE": { "country": "Niger", "code": "NE" }, 
  "NF": { "country": "Norfolk Island", "code": "NF" }, 
  "NG": { "country": "Nigeria", "code": "NG" }, 
  "NI": { "country": "Nicaragua", "code": "NI" }, 
  "NL": { "country": "Netherlands", "code": "NL" }, 
  "NO": { "country": "Norway", "code": "NO" }, 
  "NP": { "country": "Nepal", "code": "NP" }, 
  "NR": { "country": "Nauru", "code": "NR" }, 
  "NU": { "country": "Niue", "code": "NU" }, 
  "NZ": { "country": "New Zealand", "code": "NZ" }, 
  "OM": { "country": "Oman", "code": "OM" }, 
  "PA": { "country": "Panama", "code": "PA" }, 
  "PE": { "country": "Peru", "code": "PE" }, 
  "PF": { "country": "French Polynesia", "code": "PF" }, 
  "PG": { "country": "Papua New Guinea", "code": "PG" }, 
  "PH": { "country": "Philippines", "code": "PH" }, 
  "PK": { "country": "Pakistan", "code": "PK" }, 
  "PL": { "country": "Poland", "code": "PL" }, 
  "PM": { "country": "Saint Pierre and Miquelon", "code": "PM" }, 
  "PN": { "country": "Pitcairn", "code": "PN" }, 
  "PS": { "country": "Palestine", "code": "PS" }, 
  "PT": { "country": "Portugal", "code": "PT" }, 
  "PY": { "country": "Paraguay", "code": "PY" }, 
  "QA": { "country": "Qatar", "code": "QA" }, 
  "RE": { "country": "Reunion", "code": "RE" }, 
  "RO": { "country": "Romania", "code": "RO" }, 
  "RS": { "country": "Serbia", "code": "RS" }, 
  "RU": { "country": "Russian Federation", "code": "RU" }, 
  "RW": { "country": "Rwanda", "code": "RW" }, 
  "SA": { "country": "Saudi Arabia", "code": "SA" }, 
  "SB": { "country": "Solomon Islands", "code": "SB" }, 
  "SC": { "country": "Seychelles", "code": "SC" }, 
  "SD": { "country": "Sudan", "code": "SD" }, 
  "SE": { "country": "Sweden", "code": "SE" }, 
  "SG": { "country": "Singapore", "code": "SG" }, 
  "SH": { "country": "Saint Helena, Ascension and Tristan da Cunha", "code": "SH" }, 
  "SI": { "country": "Slovenia", "code": "SI" }, 
  "SJ": { "country": "Svalbard and Jan Mayen", "code": "SJ" }, 
  "SK": { "country": "Slovakia", "code": "SK" }, 
  "SL": { "country": "Sierra Leone", "code": "SL" }, 
  "SM": { "country": "San Marino", "code": "SM" }, 
  "SN": { "country": "Senegal", "code": "SN" }, 
  "SO": { "country": "Somalia", "code": "SO" }, 
  "SR": { "country": "Suriname", "code": "SR" }, 
  "SS": { "country": "South Sudan", "code": "SS" }, 
  "ST": { "country": "Sao Tome and Principe", "code": "ST" }, 
  "SV": { "country": "El Salvador", "code": "SV" }, 
  "SX": { "country": "Sint Maarten (Dutch part)", "code": "SX" }, 
  "SY": { "country": "Syrian Arab Republic", "code": "SY" }, 
  "SZ": { "country": "Swaziland", "code": "SZ" }, 
  "TC": { "country": "Turks and Caicos Islands", "code": "TC" }, 
  "TD": { "country": "Chad", "code": "TD" }, 
  "TF": { "country": "French Southern Territories", "code": "TF" }, 
  "TG": { "country": "Togo", "code": "TG" }, 
  "TH": { "country": "Thailand", "code": "TH" }, 
  "TJ": { "country": "Tajikistan", "code": "TJ" }, 
  "TK": { "country": "Tokelau", "code": "TK" }, 
  "TL": { "country": "Timor-Leste", "code": "TL" }, 
  "TM": { "country": "Turkmenistan", "code": "TM" }, 
  "TN": { "country": "Tunisia", "code": "TN" }, 
  "TO": { "country": "Tonga", "code": "TO" }, 
  "TR": { "country": "Turkey", "code": "TR" }, 
  "TT": { "country": "Trinidad and Tobago", "code": "TT" }, 
  "TV": { "country": "Tuvalu", "code": "TV" }, 
  "TW": { "country": "Taiwan", "code": "TW" }, 
  "TZ": { "country": "Tanzania, United Republic of", "code": "TZ" }, 
  "UA": { "country": "Ukraine", "code": "UA" }, 
  "UG": { "country": "Uganda", "code": "UG" }, 
  "US": { "country": "United States*", "code": "US" }, 
  "UY": { "country": "Uruguay", "code": "UY" }, 
  "UZ": { "country": "Uzbekistan", "code": "UZ" }, 
  "VA": { "country": "Holy See (Vatican City State)", "code": "VA" }, 
  "VC": { "country": "Saint Vincent and the Grenadines", "code": "VC" }, 
  "VE": { "country": "Venezuela, Bolivarian Republic of", "code": "VE" }, 
  "VG": { "country": "Virgin Islands, British", "code": "VG" }, 
  "VN": { "country": "Vietnam", "code": "VN" }, 
  "VU": { "country": "Vanuatu", "code": "VU" }, 
  "WF": { "country": "Wallis and Futuna", "code": "WF" }, 
  "WS": { "country": "Samoa", "code": "WS" }, 
  "YE": { "country": "Yemen", "code": "YE" }, 
  "YT": { "country": "Mayotte", "code": "YT" }, 
  "ZA": { "country": "South Africa", "code": "ZA" }, 
  "ZM": { "country": "Zambia", "code": "ZM" }, 
  "ZW": { "country": "Zimbabwe", "code": "ZW" } 
};

module.exports = countries;